services:
  - type: web
    name: shl-recommender
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python scripts/02_build_embeddings.py
    startCommand: uvicorn src.api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: USE_LLM_RERANKING
        value: true
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: GEMINI_API_KEY
        value: AIzaSyBADMWw8fA1EjFmuMzgWtUMrGos2CJNUjY
